#### Q1. What is the mathematical formula for a linear SVM?

The mathematical formula for a linear Support Vector Machine (SVM) can be expressed as follows:

For classification:

- y = sign(w·x + b),

where x represents the input variables, w is the weight vector perpendicular to the hyperplane, ' · 'denotes the dot product, b is the bias term, and y takes values of either -1 or +1, representing the two classes.

In equation form:

yi = sign(w·xi + b),

where (xi, yi) are the training examples.

The goal of SVM is to find the optimal weight vector w and bias term b that minimize the misclassification errors while maximizing the margin between classes. The optimization problem involves solving for w and b that satisfy certain constraints, which ensure correct classification and margin maximization.

#### Q2. What is the objective function of a linear SVM?

The objective function of a linear Support Vector Machine (SVM) is to find the optimal hyperplane that maximizes the margin between the classes while minimizing the classification error. The objective function can be written as:

Minimize: 1/2*||w||^2,

Subject to: yi(w · xi + b) ≥ 1,

where (xi, yi) are the training examples, w is the weight vector perpendicular to the hyperplane, · denotes the dot product, b is the bias term, ||w||^2 represents the regularization term, and yi takes values of either -1 or +1, representing the two classes.

The objective function aims to minimize the norm of the weight vector, which corresponds to the complexity of the model, while satisfying the constraint that all training examples lie on the correct side of the decision boundary with a margin of at least 1. The constraint ensures that the SVM achieves good generalization and separates the classes accurately.

The objective function of a linear SVM can be optimized using various optimization techniques, such as quadratic programming or gradient descent, to find the optimal values of the weight vector w and bias term b that fulfill the margin and classification constraints.

#### Q3. What is the kernel trick in SVM?

The kernel trick is a technique used in Support Vector Machines (SVM) that allows them to handle non-linearly separable data without explicitly transforming the input data into a higher-dimensional feature space. It enables SVM to efficiently compute the decision boundary and make predictions based on the transformed feature space without explicitly calculating the transformed feature vectors.

In traditional SVM, the decision boundary is determined by the dot product of the input feature vectors. However, when dealing with complex, non-linear relationships, it may be difficult to find a linear decision boundary in the original feature space.

The kernel trick solves this problem by introducing a kernel function, denoted as K(x_i, x_j), which calculates the dot product between the transformed feature vectors in a higher-dimensional space. This allows SVM to implicitly map the input data into a higher-dimensional feature space where it might be linearly separable.

By using the kernel function, the SVM algorithm can compute the decision boundary in the transformed feature space without explicitly calculating the transformed feature vectors. This approach saves computational resources and avoids the need to define the transformation explicitly.

Commonly used kernel functions include:

- Linear Kernel: K(xi, xj) = xi · xj, which is equivalent to the standard dot product between the original feature vectors.
- Polynomial Kernel: K(xi, xj) = (γ(xi · xj) + r)^d, where γ, r, and d are kernel parameters.
- Radial Basis Function (RBF) Kernel: K(xi, xj) = exp(-γ ||xi - xj||^2), where γ is a kernel parameter that controls the smoothness of the decision boundary.
- Sigmoid Kernel: K(xi, xj) = tanh(γ(xi · xj) + r), where γ and r are kernel parameters.

By selecting an appropriate kernel function, SVM can effectively handle non-linear decision boundaries and capture complex relationships between the input variables, allowing for more accurate classification or regression tasks.

#### Q4. What is the role of support vectors in SVM Explain with example 

Support vectors play a crucial role in Support Vector Machines (SVM). They are the training examples that are closest to the decision boundary or lie within the margin. In SVM, the decision boundary is determined by these support vectors.

To explain the role of support vectors, let's consider a simple example. Suppose we have a binary classification problem with two classes, represented by red and blue data points in a two-dimensional space.

In SVM, the algorithm aims to find the optimal decision boundary, also known as the hyperplane, that separates these two classes. The hyperplane is defined by a weight vector w and a bias term b.

During the training process, SVM identifies the support vectors, which are the data points closest to the decision boundary. These support vectors have a significant influence on determining the position and orientation of the decision boundary.

The support vectors are the critical data points because they define the margin. The margin is the region between the two parallel hyperplanes, one for each class, that are maximally distant from each other while not including any data points.

The support vectors lie on or within the margin boundaries. They are the data points that have the potential to affect the decision boundary if their positions change. Other data points that are not support vectors do not affect the decision boundary since they do not lie on or within the margin.

The importance of support vectors lies in their influence on the SVM model's generalization performance. By focusing on the support vectors, SVM effectively handles the training data and builds a decision boundary that is less sensitive to outliers and noise. This property leads to a more robust and accurate model

#### Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in SVM?

Certainly! Let's illustrate the concepts of the hyperplane, marginal plane, soft margin, and hard margin in SVM with examples and graphs.

- Hyperplane: The hyperplane is the decision boundary that separates the classes in SVM. In a binary classification problem with two input features, the hyperplane is a line. In a three-dimensional space with three input features, the hyperplane is a plane.

Example: Consider a simple example with two classes, represented by red and blue points. The graph below shows a linear hyperplane (a line) that separates the classes. The hyperplane is denoted by the black line.


- Margin: The margin is the region between the two parallel planes/hyperplanes that are maximally distant from each other while not including any data points. It is defined by the support vectors, which are the data points lying on or within the margin boundaries.

Example: The graph below shows a linear SVM with the margin denoted by the shaded region. The support vectors are the points on or within the margin boundaries (highlighted by circles).


- Hard Margin: In a hard margin SVM, the goal is to find a hyperplane that perfectly separates the classes without allowing any misclassifications. This approach assumes that the data is linearly separable without any overlapping points.

Example: The graph below illustrates a hard margin SVM with a linearly separable dataset. The hyperplane perfectly separates the red and blue points without any misclassifications.


- Soft Margin: In a soft margin SVM, a certain amount of misclassification is allowed to find a hyperplane that separates the classes while allowing for some tolerance for errors. Soft margin SVMs are used when the data points are not linearly separable or when dealing with noisy datasets.

Example: The graph below depicts a soft margin SVM with a linearly non-separable dataset. The misclassified points, denoted by the circles, are allowed within the margin, resulting in a more flexible decision boundary.


The examples and graphs above demonstrate the concepts of the hyperplane, marginal plane, soft margin, and hard margin in SVM. They showcase different scenarios in SVM, from perfectly separable data with a hard margin to non-separable data with a soft margin that allows for misclassifications within the margin.

#### Q6. SVM Implementation through Iris dataset.

Bonus task: Implement a linear SVM classifier from scratch using Python and compare its
performance with the scikit-learn implementation

- Load the iris dataset from the scikit-learn library and split it into a training set and a testing set

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, train_size=0.2 )

In [16]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
91           6.1          3.0           4.6          1.4
41           4.5          2.3           1.3          0.3
58           6.6          2.9           4.6          1.3
90           5.5          2.6           4.4          1.2
48           5.3          3.7           1.5          0.2

In [18]:
y_train.head()

91    versicolor
41        setosa
58    versicolor
90    versicolor
48        setosa
Name: species, dtype: object

#### - Train a linear SVM classifier on the training set and predict the labels for the testing set

In [20]:
from sklearn.svm import SVC

In [21]:
svc = SVC(kernel = 'linear')

In [23]:
svc.fit(X_train, y_train)

SVC(kernel='linear')

In [24]:
svc.coef_

array([[ 0.04640291,  0.25102128, -0.88984179, -0.37711427],
       [ 0.05546538,  0.12007903, -0.52236181, -0.2676029 ],
       [ 0.69910361,  0.17726741, -1.58142662, -1.15508309]])

In [29]:
y_pred = svc.predict(X_test)

In [33]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [35]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        43
  versicolor       1.00      0.92      0.96        39
   virginica       0.93      1.00      0.96        38

    accuracy                           0.97       120
   macro avg       0.98      0.97      0.97       120
weighted avg       0.98      0.97      0.97       120

[[43  0  0]
 [ 0 36  3]
 [ 0  0 38]]


#### - Compute the accuracy of the model on the testing set

In [37]:
print(accuracy_score(y_test, y_pred))

0.975


#### - Plot the decision boundaries of the trained model using two of the features

#### - Try different values of the regularisation parameter C and see how it affects the performance of the model.

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
param_grid = {'C': [0.1, 1, 10, 100, 1000]}

In [40]:
grid = GridSearchCV(SVC(), param_grid = param_grid, refit= True , cv = 5, verbose = 3)

In [42]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END .............................C=0.1;, score=0.333 total time=   0.0s
[CV 2/5] END .............................C=0.1;, score=0.333 total time=   0.0s
[CV 3/5] END .............................C=0.1;, score=0.333 total time=   0.0s
[CV 4/5] END .............................C=0.1;, score=0.667 total time=   0.0s
[CV 5/5] END .............................C=0.1;, score=0.667 total time=   0.0s
[CV 1/5] END ...............................C=1;, score=1.000 total time=   0.0s
[CV 2/5] END ...............................C=1;, score=1.000 total time=   0.0s
[CV 3/5] END ...............................C=1;, score=1.000 total time=   0.0s
[CV 4/5] END ...............................C=1;, score=0.833 total time=   0.0s
[CV 5/5] END ...............................C=1;, score=0.833 total time=   0.0s
[CV 1/5] END ..............................C=10;, score=1.000 total time=   0.0s
[CV 2/5] END ..............................C=10;,

GridSearchCV(cv=5, estimator=SVC(), param_grid={'C': [0.1, 1, 10, 100, 1000]},
             verbose=3)

In [46]:
# prediction

y_pred2 = grid.predict(X_test)

In [48]:
print(classification_report(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        43
  versicolor       1.00      0.95      0.97        39
   virginica       0.95      1.00      0.97        38

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

[[43  0  0]
 [ 0 37  2]
 [ 0  0 38]]


In [49]:
accuracy_score(y_test, y_pred2)

0.9833333333333333

Interpretation: We can clearly see that using gridsearch cv for C parameter our model accuracy increase from 97.5 to 98.33.